### ISSUE TITLE
how to update openapi-schemas for OpenAPI spec v3.1?

### ISSUE THREAD

**Issue by ghost** [APIDevTools/openapi-schemas#1]
Should the existing `openAPIv3` export now point to the 3.1 spec? 

Or should an `openAPIv31` export be added?

**Comment by seriousme** [comment]
https://spec.openapis.org/oas/v3.1.0#versions says:

>The OpenAPI Specification is versioned using a major.minor.patch versioning scheme. The major.minor portion of the version string (for example 3.1) SHALL designate the OAS feature set. .patch versions address errors in, or provide clarifications to, this document, not the feature set. Tooling which supports OAS 3.1 SHOULD be compatible with all OAS 3.1.* versions. The patch version SHOULD NOT be considered by tooling, making no distinction between 3.1.0 and 3.1.1 for example.

>Occasionally, non-backwards compatible changes may be made in minor versions of the OAS where impact is believed to be low relative to the benefit provided.

One of these changes is that 3.0.x supports more data types than 3.1.x so I strict parser on 3.1 will fail to parse a 3.0 spec with e.g. data type `binary`

So I'd think it should be openAPIv31 ;-)
@philsturgeon do you have any view on this ?

Kind regards,
Hans

**Comment by philsturgeon** [comment]
People will need to use 3.0 and 3.1 so best make a new one.
